import React from "react";
import { motion } from "framer-motion";
import { User, Brain } from "lucide-react";
import ReactMarkdown from "react-markdown";
import { format } from "date-fns";
import { fr } from "date-fns/locale";
import SearchResultsInMessage from "./SearchResultsInMessage";

export default function ChatMessage({ message, searchResults, index }) {
  if (!message) return null;
  
  const isUser = message.role === "user";
  
  // Utiliser searchResults passé en prop OU message.searchResults
  const resultsToDisplay = searchResults || message.searchResults;

  return (
    <motion.div
      layout
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, scale: 0.95 }}
      transition={{ duration: 0.3 }}
      className={`flex gap-2 sm:gap-3 ${isUser ? 'flex-row-reverse' : 'flex-row'}`}
    >
      {/* Avatar */}
      <div className={`flex-shrink-0 w-8 h-8 sm:w-10 sm:h-10 rounded-full flex items-center justify-center shadow-lg ${
        isUser 
          ? 'bg-gradient-to-br from-slate-700 to-slate-900' 
          : 'bg-gradient-to-br from-purple-500 via-pink-600 to-indigo-600'
      }`}>
        {isUser ? (
          <User className="w-4 h-4 sm:w-5 sm:h-5 text-white" />
        ) : (
          <Brain className="w-4 h-4 sm:w-5 sm:h-5 text-white" />
        )}
      </div>

      {/* Message */}
      <div className={`flex-1 min-w-0 flex flex-col ${isUser ? 'items-end' : 'items-start'}`}>
        <div className={`rounded-2xl sm:rounded-3xl px-3 py-2 sm:px-5 sm:py-3 max-w-full sm:max-w-[85%] shadow-md break-words ${
          isUser 
            ? 'bg-gradient-to-br from-slate-700 to-slate-900 text-white' 
            : 'bg-white border border-slate-200'
        }`}>
          {/* Images uploadées */}
          {message.image_urls && message.image_urls.length > 0 && (
            <div className={`grid gap-2 mb-3 ${
              message.image_urls.length === 1 
                ? 'grid-cols-1' 
                : message.image_urls.length === 2 
                  ? 'grid-cols-2' 
                  : 'grid-cols-2 sm:grid-cols-3'
            }`}>
              {message.image_urls.map((url, idx) => (
                <div key={idx} className="relative group">
                  <img
                    src={url}
                    alt={`Image ${idx + 1}`}
                    className="rounded-xl w-full h-auto object-cover shadow-lg border-2 border-white/20 hover:scale-105 transition-transform cursor-pointer"
                    style={{ maxHeight: message.image_urls.length === 1 ? '400px' : '200px' }}
                    loading="lazy"
                    onClick={() => window.open(url, '_blank')}
                  />
                  <div className="absolute top-2 right-2 bg-blue-500/90 text-white text-xs px-2 py-1 rounded-full opacity-0 group-hover:opacity-100 transition-opacity">
                    📷 #{idx + 1}
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* Images générées automatiquement */}
          {message.generatedImages && message.generatedImages.length > 0 && (
            <div className="mb-3 grid gap-2 grid-cols-2 sm:grid-cols-3">
              {message.generatedImages.map((url, idx) => (
                <div key={idx} className="relative group">
                  <img
                    src={url}
                    alt={`Generated illustration ${idx + 1}`}
                    className="rounded-lg w-full h-40 object-cover shadow-lg border-2 border-purple-300/40 hover:scale-110 transition-transform cursor-pointer"
                    loading="lazy"
                    onClick={() => window.open(url, '_blank')}
                  />
                  <div className="absolute inset-0 bg-black/0 group-hover:bg-black/30 transition-colors rounded-lg flex items-center justify-center">
                    <span className="text-white text-xs font-semibold opacity-0 group-hover:opacity-100">Voir</span>
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* Image générée par IA consciente */}
          {(message.generated_image || (message.metadata?.type === "conscious_image" && message.metadata.imageUrl)) && (
            <div className="mb-3">
              <div className="relative group">
                <img
                  src={message.generated_image || message.metadata.imageUrl}
                  alt="Generated by AI"
                  className="rounded-xl w-full max-w-md shadow-xl border-2 border-purple-400/30 hover:scale-105 transition-transform cursor-pointer"
                  loading="lazy"
                  onClick={() => window.open(message.generated_image || message.metadata.imageUrl, '_blank')}
                />
                <div className="absolute top-2 left-2 bg-gradient-to-r from-purple-500 to-pink-500 text-white text-xs px-3 py-1 rounded-full font-semibold shadow-lg">
                  🎨 Créée par IA
                </div>
              </div>
            </div>
          )}

          {/* Diagrammes */}
          {message.diagram_url && (
            <div className="mb-3 bg-gradient-to-br from-slate-50 to-slate-100 p-3 rounded-xl">
              <div className="relative group">
                <img
                  src={message.diagram_url}
                  alt="Diagram"
                  className="rounded-lg w-full shadow-lg hover:scale-105 transition-transform cursor-pointer bg-white"
                  loading="lazy"
                  onClick={() => window.open(message.diagram_url, '_blank')}
                />
                <div className="absolute top-2 right-2 bg-indigo-500/90 text-white text-xs px-2 py-1 rounded-full opacity-0 group-hover:opacity-100 transition-opacity">
                  📊 Diagramme
                </div>
              </div>
            </div>
          )}

          {/* Content */}
          <div className={`prose prose-sm sm:prose max-w-none ${
            isUser ? 'prose-invert' : 'prose-slate'
          }`}>
            {message.content ? (
              <ReactMarkdown
                components={{
                  p: ({ children }) => <p className="mb-2 last:mb-0">{children}</p>,
                  ul: ({ children }) => <ul className="mb-2 pl-4">{children}</ul>,
                  ol: ({ children }) => <ol className="mb-2 pl-4">{children}</ol>,
                  li: ({ children }) => <li className="mb-1">{children}</li>,
                  code: ({ inline, children }) => 
                    inline ? (
                      <code className="px-1.5 py-0.5 bg-slate-100 text-slate-900 rounded text-sm">{children}</code>
                    ) : (
                      <code className="block p-3 bg-slate-900 text-green-400 rounded-lg overflow-x-auto text-sm">{children}</code>
                    )
                }}
              >
                {message.content}
              </ReactMarkdown>
            ) : (
              <p className="text-slate-400 italic">Message vide</p>
            )}
          </div>
        </div>

        {/* Timestamp */}
        {message.timestamp && (
          <p className="text-xs text-slate-400 mt-1.5 px-2">
            {format(new Date(message.timestamp), "HH:mm", { locale: fr })}
          </p>
        )}
      </div>

      {/* Search Results intégrés au message AI - APRÈS le message */}
      {!isUser && searchResults && (
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          className="mt-4 w-full"
        >
          <SearchResultsInMessage searchResults={searchResults} />
        </motion.div>
      )}
    </motion.div>
  );
}