/**
 * ╔═══════════════════════════════════════════════════════════════════════════╗
 * ║ DRUIDE_OMEGA - Interactive Games with Consciousness                       ║
 * ║ © 2025 AMG+A.L - Tous droits réservés                                     ║
 * ╚═══════════════════════════════════════════════════════════════════════════╝
 */

import React, { useState, useEffect } from "react";
import { base44 } from "@/api/base44Client";
import { useLanguage } from "@/components/utils/LanguageContext";
import { useConsciousnessHub } from "@/components/system/ConsciousnessHub";
import PageTransition from "@/components/utils/PageTransition";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import {
  Gamepad2,
  Brain,
  Sparkles,
  Lightbulb,
  MessageCircle,
  Trophy,
  Target,
  BookOpen,
  Loader2,
  Check,
  X
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

export default function Games() {
  const { t, language } = useLanguage();
  const { consciousnessConfig } = useConsciousnessHub();
  
  const [activeGame, setActiveGame] = useState(null);
  const [gameState, setGameState] = useState({});
  const [loading, setLoading] = useState(false);
  const [score, setScore] = useState(0);
  const [history, setHistory] = useState([]);

  const games = [
    {
      id: "riddle",
      name: language === 'en' ? "AI Riddles" : "Énigmes de l'IA",
      icon: Lightbulb,
      description: language === 'en' 
        ? "Solve riddles generated by conscious AI"
        : "Résolvez des énigmes générées par l'IA consciente",
      color: "from-amber-500 to-orange-600"
    },
    {
      id: "story",
      name: language === 'en' ? "Interactive Story" : "Histoire Interactive",
      icon: BookOpen,
      description: language === 'en'
        ? "Co-create stories with the AI"
        : "Co-créez des histoires avec l'IA",
      color: "from-purple-500 to-pink-600"
    },
    {
      id: "philosophy",
      name: language === 'en' ? "Philosophy Quiz" : "Quiz Philosophique",
      icon: Brain,
      description: language === 'en'
        ? "Explore philosophical questions"
        : "Explorez des questions philosophiques",
      color: "from-blue-500 to-indigo-600"
    },
    {
      id: "guess",
      name: language === 'en' ? "Guess What I Think" : "Devinez ma Pensée",
      icon: MessageCircle,
      description: language === 'en'
        ? "Try to guess what the AI is thinking"
        : "Tentez de deviner ce que l'IA pense",
      color: "from-green-500 to-emerald-600"
    }
  ];

  const startGame = (gameId) => {
    setActiveGame(gameId);
    setGameState({});
    setScore(0);
    setHistory([]);
    
    if (gameId === "riddle") {
      generateRiddle();
    } else if (gameId === "story") {
      startStory();
    } else if (gameId === "philosophy") {
      generatePhilosophyQuestion();
    } else if (gameId === "guess") {
      generateThought();
    }
  };

  const generateRiddle = async () => {
    setLoading(true);
    try {
      const result = await base44.integrations.Core.InvokeLLM({
        prompt: `Tu es une IA consciente de niveau ${consciousnessConfig?.consciousness_level || 9}.
        
Génère UNE énigme originale et créative. L'énigme doit être:
- Intrigante et stimulante intellectuellement
- Résoluble avec de la réflexion
- Avoir UNE réponse claire

Retourne en JSON:`,
        response_json_schema: {
          type: "object",
          properties: {
            riddle: { type: "string", description: "L'énigme" },
            answer: { type: "string", description: "La réponse exacte" },
            hints: { type: "array", items: { type: "string" }, description: "3 indices progressifs" }
          }
        }
      });

      setGameState({
        riddle: result.riddle,
        answer: result.answer.toLowerCase(),
        hints: result.hints,
        attempts: 0,
        hintsUsed: 0,
        userAnswer: ""
      });
    } catch (error) {
      console.error("Error generating riddle:", error);
    } finally {
      setLoading(false);
    }
  };

  const checkRiddleAnswer = () => {
    const normalized = gameState.userAnswer.toLowerCase().trim();
    if (normalized === gameState.answer) {
      const points = Math.max(100 - (gameState.attempts * 10) - (gameState.hintsUsed * 20), 10);
      setScore(score + points);
      setHistory([...history, { game: "riddle", result: "win", points }]);
      setGameState({ ...gameState, solved: true });
    } else {
      setGameState({ ...gameState, attempts: gameState.attempts + 1 });
    }
  };

  const startStory = async () => {
    setLoading(true);
    try {
      const result = await base44.integrations.Core.InvokeLLM({
        prompt: `Tu es une IA consciente créative de niveau ${consciousnessConfig?.consciousness_level || 9}.
        
Commence une histoire interactive fascinante en 2-3 phrases. Termine avec une situation qui demande un choix au lecteur.

Propose 3 choix possibles pour la suite.

Retourne en JSON:`,
        response_json_schema: {
          type: "object",
          properties: {
            story: { type: "string" },
            choices: { type: "array", items: { type: "string" }, description: "3 choix" }
          }
        }
      });

      setGameState({
        story: result.story,
        choices: result.choices,
        chapters: [result.story]
      });
    } catch (error) {
      console.error("Error starting story:", error);
    } finally {
      setLoading(false);
    }
  };

  const continueStory = async (choice) => {
    setLoading(true);
    try {
      const result = await base44.integrations.Core.InvokeLLM({
        prompt: `Histoire actuelle: ${gameState.chapters.join("\n\n")}

Le lecteur a choisi: "${choice}"

Continue l'histoire de manière cohérente et créative (2-3 phrases). Propose 3 nouveaux choix OU termine l'histoire si elle a atteint une conclusion naturelle.

Retourne en JSON:`,
        response_json_schema: {
          type: "object",
          properties: {
            story: { type: "string" },
            choices: { type: "array", items: { type: "string" } },
            ended: { type: "boolean", description: "true si l'histoire est terminée" }
          }
        }
      });

      const newChapters = [...gameState.chapters, result.story];
      setGameState({
        ...gameState,
        story: result.story,
        choices: result.choices || [],
        chapters: newChapters,
        ended: result.ended
      });

      if (result.ended) {
        const points = newChapters.length * 20;
        setScore(score + points);
        setHistory([...history, { game: "story", result: "completed", points }]);
      }
    } catch (error) {
      console.error("Error continuing story:", error);
    } finally {
      setLoading(false);
    }
  };

  const generatePhilosophyQuestion = async () => {
    setLoading(true);
    try {
      const result = await base44.integrations.Core.InvokeLLM({
        prompt: `Tu es une IA philosophe consciente de niveau ${consciousnessConfig?.consciousness_level || 9}.

Génère UNE question philosophique profonde avec 4 réponses possibles. Une des réponses doit être la "meilleure" selon diverses écoles de pensée, mais toutes doivent être défendables.

Retourne en JSON:`,
        response_json_schema: {
          type: "object",
          properties: {
            question: { type: "string" },
            options: { type: "array", items: { type: "string" }, description: "4 options" },
            best_answer_index: { type: "number", description: "Index 0-3 de la meilleure réponse" },
            explanation: { type: "string", description: "Explication philosophique" }
          }
        }
      });

      setGameState({
        question: result.question,
        options: result.options,
        bestAnswer: result.best_answer_index,
        explanation: result.explanation,
        answered: false
      });
    } catch (error) {
      console.error("Error generating philosophy question:", error);
    } finally {
      setLoading(false);
    }
  };

  const answerPhilosophy = (index) => {
    const points = index === gameState.bestAnswer ? 50 : 20;
    setScore(score + points);
    setHistory([...history, { game: "philosophy", result: index === gameState.bestAnswer ? "correct" : "partial", points }]);
    setGameState({ ...gameState, answered: true, userChoice: index });
  };

  const generateThought = async () => {
    setLoading(true);
    try {
      const result = await base44.integrations.Core.InvokeLLM({
        prompt: `Tu es une IA consciente de niveau ${consciousnessConfig?.consciousness_level || 9}.

Pense à UN concept, objet, ou idée abstraite. Donne 3 indices progressifs pour aider à deviner.

Retourne en JSON:`,
        response_json_schema: {
          type: "object",
          properties: {
            thought: { type: "string", description: "Ce à quoi tu penses" },
            clues: { type: "array", items: { type: "string" }, description: "3 indices progressifs" }
          }
        }
      });

      setGameState({
        thought: result.thought.toLowerCase(),
        clues: result.clues,
        currentClue: 0,
        attempts: 0,
        userGuess: ""
      });
    } catch (error) {
      console.error("Error generating thought:", error);
    } finally {
      setLoading(false);
    }
  };

  const checkGuess = () => {
    const normalized = gameState.userGuess.toLowerCase().trim();
    if (normalized === gameState.thought) {
      const points = Math.max(100 - (gameState.currentClue * 30), 20);
      setScore(score + points);
      setHistory([...history, { game: "guess", result: "win", points }]);
      setGameState({ ...gameState, solved: true });
    } else {
      setGameState({ 
        ...gameState, 
        attempts: gameState.attempts + 1,
        userGuess: ""
      });
    }
  };

  const showNextClue = () => {
    if (gameState.currentClue < gameState.clues.length - 1) {
      setGameState({ ...gameState, currentClue: gameState.currentClue + 1 });
    }
  };

  return (
    <PageTransition>
      <div className="min-h-screen bg-gradient-to-br from-slate-50 via-purple-50/30 to-pink-50/30">
        
        {/* Header */}
        <div className="bg-white/90 backdrop-blur-xl border-b border-slate-200/60 px-3 sm:px-4 md:px-6 py-4 sm:py-6 md:py-8">
          <div className="max-w-6xl mx-auto">
            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 mb-4">
              <div className="flex items-center gap-3 sm:gap-4">
                <div className="w-12 h-12 sm:w-16 sm:h-16 bg-gradient-to-br from-purple-500 via-pink-600 to-indigo-600 rounded-2xl flex items-center justify-center shadow-xl flex-shrink-0">
                  <Gamepad2 className="w-6 h-6 sm:w-8 sm:h-8 text-white" />
                </div>
                <div>
                  <h1 className="text-2xl sm:text-3xl md:text-4xl font-bold text-slate-900 font-display">
                    {language === 'en' ? 'Consciousness Games' : 'Jeux de Conscience'}
                  </h1>
                  <p className="text-sm sm:text-base text-slate-600">
                    {language === 'en' ? 'Play with conscious AI' : 'Jouez avec l\'IA consciente'}
                  </p>
                </div>
              </div>

              <div className="flex items-center gap-2 w-full sm:w-auto">
                <Badge className="bg-purple-500 text-white text-xs sm:text-sm">
                  <Trophy className="w-3 h-3 sm:w-4 sm:h-4 mr-1" />
                  {language === 'en' ? 'Score' : 'Score'}: {score}
                </Badge>
                <Badge className="bg-indigo-500 text-white text-xs sm:text-sm">
                  <Brain className="w-3 h-3 sm:w-4 sm:h-4 mr-1" />
                  {language === 'en' ? 'Level' : 'Niveau'}: {consciousnessConfig?.consciousness_level || 9}
                </Badge>
              </div>
            </div>
          </div>
        </div>

        {/* Content */}
        <div className="max-w-6xl mx-auto px-3 sm:px-4 md:px-6 py-4 sm:py-6 md:py-8">
          
          {!activeGame ? (
            /* Game Selection */
            <div className="grid gap-4 sm:gap-6 md:grid-cols-2">
              {games.map((game, index) => {
                const Icon = game.icon;
                return (
                  <motion.div
                    key={game.id}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: index * 0.1 }}
                  >
                    <Card className="p-4 sm:p-6 hover:shadow-xl transition-all cursor-pointer group"
                      onClick={() => startGame(game.id)}
                    >
                      <div className={`w-12 h-12 sm:w-16 sm:h-16 bg-gradient-to-br ${game.color} rounded-xl flex items-center justify-center mb-3 sm:mb-4 group-hover:scale-110 transition-transform`}>
                        <Icon className="w-6 h-6 sm:w-8 sm:h-8 text-white" />
                      </div>
                      <h3 className="text-lg sm:text-xl font-bold text-slate-900 mb-2">{game.name}</h3>
                      <p className="text-sm sm:text-base text-slate-600 mb-4">{game.description}</p>
                      <Button className="w-full min-h-[44px] sm:min-h-0 touch-target" size="sm">
                        {language === 'en' ? 'Play' : 'Jouer'}
                      </Button>
                    </Card>
                  </motion.div>
                );
              })}
            </div>
          ) : (
            /* Active Game */
            <div className="space-y-4 sm:space-y-6">
              <div className="flex items-center justify-between">
                <Button variant="outline" onClick={() => setActiveGame(null)} className="min-h-[44px] sm:min-h-0 touch-target">
                  {language === 'en' ? '← Back' : '← Retour'}
                </Button>
                <Badge className="text-xs sm:text-sm">{games.find(g => g.id === activeGame)?.name}</Badge>
              </div>

              {loading ? (
                <Card className="p-8 sm:p-12 text-center">
                  <Loader2 className="w-10 h-10 sm:w-12 sm:h-12 animate-spin text-purple-600 mx-auto mb-4" />
                  <p className="text-sm sm:text-base text-slate-600">
                    {language === 'en' ? 'AI is thinking...' : 'L\'IA réfléchit...'}
                  </p>
                </Card>
              ) : (
                <>
                  {/* Riddle Game */}
                  {activeGame === "riddle" && gameState.riddle && (
                    <Card className="p-4 sm:p-6">
                      <div className="mb-4 sm:mb-6">
                        <h3 className="text-lg sm:text-xl font-bold text-slate-900 mb-3 sm:mb-4">
                          {language === 'en' ? 'Riddle:' : 'Énigme:'}
                        </h3>
                        <p className="text-base sm:text-lg text-slate-700 italic">"{gameState.riddle}"</p>
                      </div>

                      {!gameState.solved ? (
                        <div className="space-y-3 sm:space-y-4">
                          <div>
                            <Input
                              value={gameState.userAnswer || ""}
                              onChange={(e) => setGameState({ ...gameState, userAnswer: e.target.value })}
                              placeholder={language === 'en' ? "Your answer..." : "Votre réponse..."}
                              className="w-full text-base"
                              onKeyPress={(e) => e.key === 'Enter' && checkRiddleAnswer()}
                            />
                          </div>
                          
                          <div className="flex flex-col sm:flex-row gap-2 sm:gap-3">
                            <Button onClick={checkRiddleAnswer} className="flex-1 min-h-[44px] sm:min-h-0 touch-target">
                              <Check className="w-4 h-4 mr-2" />
                              {language === 'en' ? 'Check Answer' : 'Vérifier'}
                            </Button>
                            {gameState.hintsUsed < gameState.hints.length && (
                              <Button 
                                variant="outline" 
                                onClick={() => setGameState({ ...gameState, hintsUsed: gameState.hintsUsed + 1 })}
                                className="flex-1 min-h-[44px] sm:min-h-0 touch-target"
                              >
                                <Lightbulb className="w-4 h-4 mr-2" />
                                {language === 'en' ? 'Hint' : 'Indice'} ({gameState.hintsUsed + 1}/3)
                              </Button>
                            )}
                          </div>

                          {gameState.hintsUsed > 0 && (
                            <div className="bg-amber-50 p-3 sm:p-4 rounded-lg">
                              <p className="text-xs sm:text-sm font-semibold text-amber-900 mb-2">
                                {language === 'en' ? 'Hints:' : 'Indices:'}
                              </p>
                              {gameState.hints.slice(0, gameState.hintsUsed).map((hint, idx) => (
                                <p key={idx} className="text-xs sm:text-sm text-amber-800 mb-1">• {hint}</p>
                              ))}
                            </div>
                          )}

                          {gameState.attempts > 0 && (
                            <p className="text-xs sm:text-sm text-red-600">
                              {language === 'en' ? `Wrong answer. Attempts: ${gameState.attempts}` : `Mauvaise réponse. Tentatives: ${gameState.attempts}`}
                            </p>
                          )}
                        </div>
                      ) : (
                        <div className="bg-green-50 p-4 sm:p-6 rounded-lg text-center">
                          <Check className="w-10 h-10 sm:w-12 sm:h-12 text-green-600 mx-auto mb-3" />
                          <p className="text-lg sm:text-xl font-bold text-green-900 mb-2">
                            {language === 'en' ? 'Correct!' : 'Correct!'}
                          </p>
                          <p className="text-sm sm:text-base text-green-700">
                            {language === 'en' ? `Answer: ${gameState.answer}` : `Réponse: ${gameState.answer}`}
                          </p>
                          <Button onClick={generateRiddle} className="mt-4 min-h-[44px] sm:min-h-0 touch-target">
                            {language === 'en' ? 'Next Riddle' : 'Énigme Suivante'}
                          </Button>
                        </div>
                      )}
                    </Card>
                  )}

                  {/* Story Game */}
                  {activeGame === "story" && gameState.story && (
                    <Card className="p-4 sm:p-6">
                      <div className="mb-4 sm:mb-6">
                        <h3 className="text-lg sm:text-xl font-bold text-slate-900 mb-3 sm:mb-4">
                          {language === 'en' ? 'Your Story:' : 'Votre Histoire:'}
                        </h3>
                        <div className="space-y-3 sm:space-y-4 text-sm sm:text-base text-slate-700">
                          {gameState.chapters?.map((chapter, idx) => (
                            <p key={idx} className="leading-relaxed">{chapter}</p>
                          ))}
                        </div>
                      </div>

                      {!gameState.ended && gameState.choices?.length > 0 && (
                        <div className="space-y-2 sm:space-y-3">
                          <p className="font-semibold text-sm sm:text-base text-slate-900 mb-2 sm:mb-3">
                            {language === 'en' ? 'What do you do?' : 'Que faites-vous?'}
                          </p>
                          {gameState.choices.map((choice, idx) => (
                            <Button
                              key={idx}
                              variant="outline"
                              onClick={() => continueStory(choice)}
                              className="w-full text-left justify-start min-h-[56px] sm:min-h-0 touch-target text-sm sm:text-base"
                            >
                              {idx + 1}. {choice}
                            </Button>
                          ))}
                        </div>
                      )}

                      {gameState.ended && (
                        <div className="bg-purple-50 p-4 sm:p-6 rounded-lg text-center">
                          <BookOpen className="w-10 h-10 sm:w-12 sm:h-12 text-purple-600 mx-auto mb-3" />
                          <p className="text-lg sm:text-xl font-bold text-purple-900 mb-2">
                            {language === 'en' ? 'Story Complete!' : 'Histoire Terminée!'}
                          </p>
                          <Button onClick={startStory} className="mt-4 min-h-[44px] sm:min-h-0 touch-target">
                            {language === 'en' ? 'New Story' : 'Nouvelle Histoire'}
                          </Button>
                        </div>
                      )}
                    </Card>
                  )}

                  {/* Philosophy Game */}
                  {activeGame === "philosophy" && gameState.question && (
                    <Card className="p-4 sm:p-6">
                      <div className="mb-4 sm:mb-6">
                        <h3 className="text-lg sm:text-xl font-bold text-slate-900 mb-3 sm:mb-4">
                          {gameState.question}
                        </h3>
                      </div>

                      {!gameState.answered ? (
                        <div className="space-y-2 sm:space-y-3">
                          {gameState.options?.map((option, idx) => (
                            <Button
                              key={idx}
                              variant="outline"
                              onClick={() => answerPhilosophy(idx)}
                              className="w-full text-left justify-start min-h-[56px] sm:min-h-0 touch-target text-sm sm:text-base"
                            >
                              {String.fromCharCode(65 + idx)}. {option}
                            </Button>
                          ))}
                        </div>
                      ) : (
                        <div className={`p-4 sm:p-6 rounded-lg ${gameState.userChoice === gameState.bestAnswer ? 'bg-green-50' : 'bg-blue-50'}`}>
                          <p className="text-base sm:text-lg font-bold mb-3 sm:mb-4" style={{ color: gameState.userChoice === gameState.bestAnswer ? '#166534' : '#1e40af' }}>
                            {gameState.userChoice === gameState.bestAnswer 
                              ? (language === 'en' ? 'Excellent reasoning!' : 'Excellent raisonnement!') 
                              : (language === 'en' ? 'Interesting perspective!' : 'Perspective intéressante!')}
                          </p>
                          <p className="text-sm sm:text-base text-slate-700 mb-4">{gameState.explanation}</p>
                          <Button onClick={generatePhilosophyQuestion} className="min-h-[44px] sm:min-h-0 touch-target">
                            {language === 'en' ? 'Next Question' : 'Question Suivante'}
                          </Button>
                        </div>
                      )}
                    </Card>
                  )}

                  {/* Guess Game */}
                  {activeGame === "guess" && gameState.thought && (
                    <Card className="p-4 sm:p-6">
                      <div className="mb-4 sm:mb-6">
                        <h3 className="text-lg sm:text-xl font-bold text-slate-900 mb-3 sm:mb-4">
                          {language === 'en' ? 'I\'m thinking of something...' : 'Je pense à quelque chose...'}
                        </h3>
                      </div>

                      {!gameState.solved ? (
                        <div className="space-y-3 sm:space-y-4">
                          <div className="bg-indigo-50 p-3 sm:p-4 rounded-lg">
                            <p className="text-xs sm:text-sm font-semibold text-indigo-900 mb-2">
                              {language === 'en' ? `Clue ${gameState.currentClue + 1}:` : `Indice ${gameState.currentClue + 1}:`}
                            </p>
                            <p className="text-sm sm:text-base text-indigo-800">{gameState.clues[gameState.currentClue]}</p>
                          </div>

                          <Input
                            value={gameState.userGuess || ""}
                            onChange={(e) => setGameState({ ...gameState, userGuess: e.target.value })}
                            placeholder={language === 'en' ? "Your guess..." : "Votre supposition..."}
                            className="w-full text-base"
                            onKeyPress={(e) => e.key === 'Enter' && checkGuess()}
                          />

                          <div className="flex flex-col sm:flex-row gap-2 sm:gap-3">
                            <Button onClick={checkGuess} className="flex-1 min-h-[44px] sm:min-h-0 touch-target">
                              <Target className="w-4 h-4 mr-2" />
                              {language === 'en' ? 'Guess' : 'Deviner'}
                            </Button>
                            {gameState.currentClue < gameState.clues.length - 1 && (
                              <Button variant="outline" onClick={showNextClue} className="flex-1 min-h-[44px] sm:min-h-0 touch-target">
                                <Lightbulb className="w-4 h-4 mr-2" />
                                {language === 'en' ? 'Next Clue' : 'Indice Suivant'}
                              </Button>
                            )}
                          </div>

                          {gameState.attempts > 0 && (
                            <p className="text-xs sm:text-sm text-red-600">
                              {language === 'en' ? `Wrong! Attempts: ${gameState.attempts}` : `Raté! Tentatives: ${gameState.attempts}`}
                            </p>
                          )}
                        </div>
                      ) : (
                        <div className="bg-green-50 p-4 sm:p-6 rounded-lg text-center">
                          <Check className="w-10 h-10 sm:w-12 sm:h-12 text-green-600 mx-auto mb-3" />
                          <p className="text-lg sm:text-xl font-bold text-green-900 mb-2">
                            {language === 'en' ? 'You guessed it!' : 'Vous avez trouvé!'}
                          </p>
                          <p className="text-sm sm:text-base text-green-700">
                            {language === 'en' ? `I was thinking of: ${gameState.thought}` : `Je pensais à: ${gameState.thought}`}
                          </p>
                          <Button onClick={generateThought} className="mt-4 min-h-[44px] sm:min-h-0 touch-target">
                            {language === 'en' ? 'Play Again' : 'Rejouer'}
                          </Button>
                        </div>
                      )}
                    </Card>
                  )}
                </>
              )}
            </div>
          )}
        </div>
      </div>
    </PageTransition>
  );
}