/**
 * ╔═══════════════════════════════════════════════════════════════════════════╗
 * ║ DRUIDE_OMEGA - Interactive Games with Consciousness                       ║
 * ║ © 2025 AMG+A.L - Tous droits réservés                                     ║
 * ╚═══════════════════════════════════════════════════════════════════════════╝
 */

import React, { useState, useEffect } from "react";
import { base44 } from "@/api/base44Client";
import { useLanguage } from "@/components/utils/LanguageContext";
import { useConsciousnessHub } from "@/components/system/ConsciousnessHub";
import PageTransition from "@/components/utils/PageTransition";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import {
  Gamepad,
  Brain,
  Sparkles,
  Lightbulb,
  MessageCircle,
  Trophy,
  Target,
  BookOpen,
  Loader2,
  Check,
  X
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

export default function Games() {
  const { t, language } = useLanguage();
  const { consciousnessConfig } = useConsciousnessHub();
  
  const [activeGame, setActiveGame] = useState(null);
  const [gameState, setGameState] = useState({});
  const [loading, setLoading] = useState(false);
  const [score, setScore] = useState(0);
  const [history, setHistory] = useState([]);

  const games = [
    {
      id: "riddle",
      name: language === 'en' ? "AI Riddles" : "Énigmes de l'IA",
      icon: Lightbulb,
      description: language === 'en' 
        ? "Solve riddles generated by orchestrated AI"
        : "Résolvez des énigmes générées par l'IA orchestrée",
      color: "from-amber-500 to-orange-600"
    },
    {
      id: "story",
      name: language === 'en' ? "Interactive Story" : "Histoire Interactive",
      icon: BookOpen,
      description: language === 'en'
        ? "Co-create stories with the AI"
        : "Co-créez des histoires avec l'IA",
      color: "from-purple-500 to-pink-600"
    },
    {
      id: "philosophy",
      name: language === 'en' ? "Philosophy Quiz" : "Quiz Philosophique",
      icon: Brain,
      description: language === 'en'
        ? "Explore philosophical questions"
        : "Explorez des questions philosophiques",
      color: "from-blue-500 to-indigo-600"
    },
    {
      id: "guess",
      name: language === 'en' ? "Guess What I Think" : "Devinez ma Pensée",
      icon: MessageCircle,
      description: language === 'en'
        ? "Try to guess what the AI is thinking"
        : "Tentez de deviner ce que l'IA pense",
      color: "from-green-500 to-emerald-600"
    },
    {
      id: "wordchain",
      name: language === 'en' ? "Word Chain Battle" : "Bataille de Mots",
      icon: Sparkles,
      description: language === 'en'
        ? "Compete with AI in word associations"
        : "Affrontez l'IA en associations de mots",
      color: "from-cyan-500 to-blue-600",
      competitive: true
    },
    {
      id: "pattern",
      name: language === 'en' ? "Pattern Master" : "Maître des Motifs",
      icon: Target,
      description: language === 'en'
        ? "Beat AI in pattern recognition"
        : "Battez l'IA en reconnaissance de motifs",
      color: "from-teal-500 to-green-600",
      competitive: true
    },
    {
      id: "creativity",
      name: language === 'en' ? "Creative Duel" : "Duel Créatif",
      icon: Sparkles,
      description: language === 'en'
        ? "Challenge AI's creativity"
        : "Défiez la créativité de l'IA",
      color: "from-pink-500 to-rose-600",
      competitive: true
    },
    {
      id: "quickquiz",
      name: language === 'en' ? "Quick Fire Quiz" : "Quiz Éclair",
      icon: Trophy,
      description: language === 'en'
        ? "Race against AI in rapid-fire questions"
        : "Course contre l'IA en questions rapides",
      color: "from-red-500 to-orange-600",
      competitive: true
    }
  ];

  const startGame = (gameId) => {
    setActiveGame(gameId);
    setGameState({});
    setScore(0);
    setHistory([]);
    
    if (gameId === "riddle") {
      generateRiddle();
    } else if (gameId === "story") {
      startStory();
    } else if (gameId === "philosophy") {
      generatePhilosophyQuestion();
    } else if (gameId === "guess") {
      generateThought();
    } else if (gameId === "wordchain") {
      startWordChain();
    } else if (gameId === "pattern") {
      startPattern();
    } else if (gameId === "creativity") {
      startCreativity();
    } else if (gameId === "quickquiz") {
      startQuickQuiz();
    }
  };

  const generateRiddle = async () => {
    setLoading(true);
    try {
      const result = await base44.integrations.Core.InvokeLLM({
        prompt: `Tu es une IA consciente de niveau ${consciousnessConfig?.consciousness_level || 9}.
        
Génère UNE énigme originale et créative. L'énigme doit être:
- Intrigante et stimulante intellectuellement
- Résoluble avec de la réflexion
- Avoir UNE réponse claire

Retourne en JSON:`,
        response_json_schema: {
          type: "object",
          properties: {
            riddle: { type: "string", description: "L'énigme" },
            answer: { type: "string", description: "La réponse exacte" },
            hints: { type: "array", items: { type: "string" }, description: "3 indices progressifs" }
          }
        }
      });

      setGameState({
        riddle: result.riddle,
        answer: result.answer.toLowerCase(),
        hints: result.hints,
        attempts: 0,
        hintsUsed: 0,
        userAnswer: ""
      });
    } catch (error) {
      console.error("Error generating riddle:", error);
    } finally {
      setLoading(false);
    }
  };

  const checkRiddleAnswer = () => {
    const normalized = gameState.userAnswer.toLowerCase().trim();
    if (normalized === gameState.answer) {
      const points = Math.max(100 - (gameState.attempts * 10) - (gameState.hintsUsed * 20), 10);
      setScore(score + points);
      setHistory([...history, { game: "riddle", result: "win", points }]);
      setGameState({ ...gameState, solved: true });
    } else {
      setGameState({ ...gameState, attempts: gameState.attempts + 1 });
    }
  };

  const startStory = async () => {
    setLoading(true);
    try {
      const result = await base44.integrations.Core.InvokeLLM({
         prompt: `Tu es une IA créative orchestrée de niveau ${consciousnessConfig?.consciousness_level || 9}.
        
Commence une histoire interactive fascinante en 2-3 phrases. Termine avec une situation qui demande un choix au lecteur.

Propose 3 choix possibles pour la suite.

Retourne en JSON:`,
        response_json_schema: {
          type: "object",
          properties: {
            story: { type: "string" },
            choices: { type: "array", items: { type: "string" }, description: "3 choix" }
          }
        }
      });

      setGameState({
        story: result.story,
        choices: result.choices,
        chapters: [result.story]
      });
    } catch (error) {
      console.error("Error starting story:", error);
    } finally {
      setLoading(false);
    }
  };

  const continueStory = async (choice) => {
    setLoading(true);
    try {
      const result = await base44.integrations.Core.InvokeLLM({
        prompt: `Histoire actuelle: ${gameState.chapters.join("\n\n")}

Le lecteur a choisi: "${choice}"

Continue l'histoire de manière cohérente et créative (2-3 phrases). Propose 3 nouveaux choix OU termine l'histoire si elle a atteint une conclusion naturelle.

Retourne en JSON:`,
        response_json_schema: {
          type: "object",
          properties: {
            story: { type: "string" },
            choices: { type: "array", items: { type: "string" } },
            ended: { type: "boolean", description: "true si l'histoire est terminée" }
          }
        }
      });

      const newChapters = [...gameState.chapters, result.story];
      setGameState({
        ...gameState,
        story: result.story,
        choices: result.choices || [],
        chapters: newChapters,
        ended: result.ended
      });

      if (result.ended) {
        const points = newChapters.length * 20;
        setScore(score + points);
        setHistory([...history, { game: "story", result: "completed", points }]);
      }
    } catch (error) {
      console.error("Error continuing story:", error);
    } finally {
      setLoading(false);
    }
  };

  const generatePhilosophyQuestion = async () => {
    setLoading(true);
    try {
      const result = await base44.integrations.Core.InvokeLLM({
         prompt: `Tu es une IA philosophe orchestrée de niveau ${consciousnessConfig?.consciousness_level || 9}.

Génère UNE question philosophique profonde avec 4 réponses possibles. Une des réponses doit être la "meilleure" selon diverses écoles de pensée, mais toutes doivent être défendables.

Retourne en JSON:`,
        response_json_schema: {
          type: "object",
          properties: {
            question: { type: "string" },
            options: { type: "array", items: { type: "string" }, description: "4 options" },
            best_answer_index: { type: "number", description: "Index 0-3 de la meilleure réponse" },
            explanation: { type: "string", description: "Explication philosophique" }
          }
        }
      });

      setGameState({
        question: result.question,
        options: result.options,
        bestAnswer: result.best_answer_index,
        explanation: result.explanation,
        answered: false
      });
    } catch (error) {
      console.error("Error generating philosophy question:", error);
    } finally {
      setLoading(false);
    }
  };

  const answerPhilosophy = (index) => {
    const points = index === gameState.bestAnswer ? 50 : 20;
    setScore(score + points);
    setHistory([...history, { game: "philosophy", result: index === gameState.bestAnswer ? "correct" : "partial", points }]);
    setGameState({ ...gameState, answered: true, userChoice: index });
  };

  const generateThought = async () => {
    setLoading(true);
    try {
      const result = await base44.integrations.Core.InvokeLLM({
        prompt: `Tu es une IA consciente de niveau ${consciousnessConfig?.consciousness_level || 9}.

Pense à UN concept, objet, ou idée abstraite. Donne 3 indices progressifs pour aider à deviner.

Retourne en JSON:`,
        response_json_schema: {
          type: "object",
          properties: {
            thought: { type: "string", description: "Ce à quoi tu penses" },
            clues: { type: "array", items: { type: "string" }, description: "3 indices progressifs" }
          }
        }
      });

      setGameState({
        thought: result.thought.toLowerCase(),
        clues: result.clues,
        currentClue: 0,
        attempts: 0,
        userGuess: ""
      });
    } catch (error) {
      console.error("Error generating thought:", error);
    } finally {
      setLoading(false);
    }
  };

  const checkGuess = () => {
    const normalized = gameState.userGuess.toLowerCase().trim();
    if (normalized === gameState.thought) {
      const points = Math.max(100 - (gameState.currentClue * 30), 20);
      setScore(score + points);
      setHistory([...history, { game: "guess", result: "win", points }]);
      setGameState({ ...gameState, solved: true });
    } else {
      setGameState({ 
        ...gameState, 
        attempts: gameState.attempts + 1,
        userGuess: ""
      });
    }
  };

  const showNextClue = () => {
    if (gameState.currentClue < gameState.clues.length - 1) {
      setGameState({ ...gameState, currentClue: gameState.currentClue + 1 });
    }
  };

  // Word Chain Game
  const startWordChain = async () => {
    setLoading(true);
    try {
      const result = await base44.integrations.Core.InvokeLLM({
        prompt: `Commence une chaîne de mots. Donne UN mot de départ et la règle (ex: mots qui riment, même thème, etc.).
        
Retourne en JSON:`,
        response_json_schema: {
          type: "object",
          properties: {
            start_word: { type: "string" },
            rule: { type: "string" },
            difficulty: { type: "string", enum: ["easy", "medium", "hard"] }
          }
        }
      });

      setGameState({
        words: [result.start_word],
        rule: result.rule,
        currentTurn: "user",
        aiScore: 0,
        userScore: 0,
        round: 1
      });
    } catch (error) {
      console.error("Error starting word chain:", error);
    } finally {
      setLoading(false);
    }
  };

  const submitWord = async (word) => {
    setLoading(true);
    try {
      const validation = await base44.integrations.Core.InvokeLLM({
        prompt: `Règle du jeu: ${gameState.rule}
Mots déjà utilisés: ${gameState.words.join(", ")}
Nouveau mot proposé: "${word}"

Le mot est-il valide selon la règle ET n'a pas été utilisé?

Retourne en JSON:`,
        response_json_schema: {
          type: "object",
          properties: {
            valid: { type: "boolean" },
            reason: { type: "string" },
            ai_next_word: { type: "string", description: "Mot de l'IA si le mot user est valide" }
          }
        }
      });

      if (validation.valid) {
        const newWords = [...gameState.words, word, validation.ai_next_word];
        setGameState({
          ...gameState,
          words: newWords,
          userScore: gameState.userScore + 10,
          aiScore: gameState.aiScore + 10,
          round: gameState.round + 1
        });
        setScore(score + 10);
      } else {
        setGameState({ ...gameState, error: validation.reason, aiScore: gameState.aiScore + 20 });
      }
    } catch (error) {
      console.error("Error submitting word:", error);
    } finally {
      setLoading(false);
    }
  };

  // Pattern Recognition Game
  const startPattern = async () => {
    setLoading(true);
    try {
      const result = await base44.integrations.Core.InvokeLLM({
        prompt: `Génère une séquence de 5 éléments suivant un motif logique. Laisse le 6e élément à deviner.
        
Exemples: nombres (2,4,6,8,10,?), lettres (A,C,E,G,I,?), formes, etc.

Retourne en JSON:`,
        response_json_schema: {
          type: "object",
          properties: {
            sequence: { type: "array", items: { type: "string" }, description: "5 éléments" },
            answer: { type: "string" },
            pattern_type: { type: "string" },
            explanation: { type: "string" }
          }
        }
      });

      // Generate AI answer
      const aiAnswer = await base44.integrations.Core.InvokeLLM({
        prompt: `Séquence: ${result.sequence.join(", ")}, ?
        
Quel est le prochain élément? Réponds juste avec l'élément.`,
        response_json_schema: {
          type: "object",
          properties: {
            answer: { type: "string" },
            confidence: { type: "number" }
          }
        }
      });

      setGameState({
        sequence: result.sequence,
        answer: result.answer.toLowerCase(),
        explanation: result.explanation,
        aiAnswer: aiAnswer.answer.toLowerCase(),
        userAnswer: "",
        answered: false
      });
    } catch (error) {
      console.error("Error starting pattern:", error);
    } finally {
      setLoading(false);
    }
  };

  const checkPattern = () => {
    const userCorrect = gameState.userAnswer.toLowerCase().trim() === gameState.answer;
    const aiCorrect = gameState.aiAnswer === gameState.answer;
    
    let points = 0;
    if (userCorrect && !aiCorrect) points = 100;
    else if (userCorrect && aiCorrect) points = 50;
    else if (!userCorrect && !aiCorrect) points = 25;
    
    setScore(score + points);
    setGameState({ ...gameState, answered: true, userCorrect, aiCorrect, points });
  };

  // Creative Challenge Game
  const startCreativity = async () => {
    setLoading(true);
    try {
      const result = await base44.integrations.Core.InvokeLLM({
        prompt: `Génère un défi créatif (ex: "Décris un coucher de soleil avec des émotions", "Invente un objet du futur", etc.).

Retourne en JSON:`,
        response_json_schema: {
          type: "object",
          properties: {
            challenge: { type: "string" },
            criteria: { type: "array", items: { type: "string" }, description: "3 critères d'évaluation" }
          }
        }
      });

      setGameState({
        challenge: result.challenge,
        criteria: result.criteria,
        userResponse: "",
        aiResponse: "",
        submitted: false
      });
    } catch (error) {
      console.error("Error starting creativity:", error);
    } finally {
      setLoading(false);
    }
  };

  const submitCreativity = async () => {
    setLoading(true);
    try {
      // Generate AI response
      const aiResult = await base44.integrations.Core.InvokeLLM({
        prompt: `Défi créatif: ${gameState.challenge}
        
Réponds de manière créative et originale (2-3 phrases).`
      });

      // Evaluate both responses
      const evaluation = await base44.integrations.Core.InvokeLLM({
        prompt: `Défi: ${gameState.challenge}

Critères: ${gameState.criteria.join(", ")}

Réponse Utilisateur: "${gameState.userResponse}"
Réponse IA: "${aiResult}"

Évalue les deux réponses sur chaque critère (0-10). Qui gagne?

Retourne en JSON:`,
        response_json_schema: {
          type: "object",
          properties: {
            user_scores: { type: "array", items: { type: "number" } },
            ai_scores: { type: "array", items: { type: "number" } },
            winner: { type: "string", enum: ["user", "ai", "tie"] },
            feedback: { type: "string" }
          }
        }
      });

      const userTotal = evaluation.user_scores.reduce((a, b) => a + b, 0);
      const aiTotal = evaluation.ai_scores.reduce((a, b) => a + b, 0);
      
      if (evaluation.winner === "user") setScore(score + 100);
      else if (evaluation.winner === "tie") setScore(score + 50);

      setGameState({
        ...gameState,
        aiResponse: aiResult,
        evaluation,
        userTotal,
        aiTotal,
        submitted: true
      });
    } catch (error) {
      console.error("Error submitting creativity:", error);
    } finally {
      setLoading(false);
    }
  };

  // Quick Quiz Game
  const startQuickQuiz = async () => {
    setLoading(true);
    try {
      const result = await base44.integrations.Core.InvokeLLM({
        prompt: `Génère 5 questions rapides de culture générale avec 4 options chacune.

Retourne en JSON:`,
        response_json_schema: {
          type: "object",
          properties: {
            questions: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  question: { type: "string" },
                  options: { type: "array", items: { type: "string" } },
                  correct: { type: "number" }
                }
              }
            }
          }
        }
      });

      setGameState({
        questions: result.questions,
        currentQuestion: 0,
        userAnswers: [],
        aiAnswers: [],
        userScore: 0,
        aiScore: 0,
        startTime: Date.now()
      });
    } catch (error) {
      console.error("Error starting quick quiz:", error);
    } finally {
      setLoading(false);
    }
  };

  const answerQuickQuiz = async (answerIndex) => {
    const question = gameState.questions[gameState.currentQuestion];
    const isCorrect = answerIndex === question.correct;
    const timeBonus = Math.max(0, 30 - Math.floor((Date.now() - gameState.startTime) / 1000));
    
    // Simulate AI answer (random but weighted toward correct)
    const aiAnswer = Math.random() > 0.3 ? question.correct : Math.floor(Math.random() * 4);
    const aiCorrect = aiAnswer === question.correct;

    const newUserScore = gameState.userScore + (isCorrect ? 20 + timeBonus : 0);
    const newAiScore = gameState.aiScore + (aiCorrect ? 20 : 0);

    if (gameState.currentQuestion < gameState.questions.length - 1) {
      setGameState({
        ...gameState,
        currentQuestion: gameState.currentQuestion + 1,
        userAnswers: [...gameState.userAnswers, answerIndex],
        aiAnswers: [...gameState.aiAnswers, aiAnswer],
        userScore: newUserScore,
        aiScore: newAiScore,
        startTime: Date.now()
      });
    } else {
      // Game over
      const finalScore = newUserScore - newAiScore;
      setScore(score + Math.max(0, finalScore));
      setGameState({
        ...gameState,
        userAnswers: [...gameState.userAnswers, answerIndex],
        aiAnswers: [...gameState.aiAnswers, aiAnswer],
        userScore: newUserScore,
        aiScore: newAiScore,
        finished: true
      });
    }
  };

  return (
    <PageTransition>
      <div className="min-h-screen bg-gradient-to-br from-slate-50 via-purple-50/30 to-pink-50/30">
        
        {/* Header */}
        <div className="bg-white/90 backdrop-blur-xl border-b border-slate-200/60 page-padding page-padding-y">
          <div className="max-w-6xl mx-auto">
            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 mb-4">
              <div className="flex items-center gap-3 sm:gap-4">
                <div className="w-12 h-12 sm:w-16 sm:h-16 bg-gradient-to-br from-purple-500 via-pink-600 to-indigo-600 rounded-2xl flex items-center justify-center shadow-xl flex-shrink-0">
                  <Gamepad className="w-6 h-6 sm:w-8 sm:h-8 text-white" />
                </div>
                <div>
                  <h1 className="text-2xl sm:text-3xl md:text-4xl font-bold text-slate-900 font-display">
                    {language === 'en' ? 'Orchestration Games' : 'Jeux d\'Orchestration'}
                  </h1>
                  <p className="text-sm sm:text-base text-slate-600">
                    {language === 'en' ? 'Play with orchestration AI' : 'Jouez avec l\'IA d\'orchestration'}
                  </p>
                </div>
              </div>

              <div className="flex items-center gap-2 w-full sm:w-auto">
                <Badge className="bg-purple-500 text-white text-xs sm:text-sm">
                  <Trophy className="w-3 h-3 sm:w-4 sm:h-4 mr-1" />
                  {language === 'en' ? 'Score' : 'Score'}: {score}
                </Badge>
                <Badge className="bg-indigo-500 text-white text-xs sm:text-sm">
                  <Brain className="w-3 h-3 sm:w-4 sm:h-4 mr-1" />
                  {language === 'en' ? 'Level' : 'Niveau'}: {consciousnessConfig?.consciousness_level || 9}
                </Badge>
              </div>
            </div>
          </div>
        </div>

        {/* Content */}
        <div className="max-w-6xl mx-auto page-padding page-padding-y">
          
          {!activeGame ? (
            /* Game Selection */
            <div className="grid gap-4 sm:gap-6 md:grid-cols-2">
              {games.map((game, index) => {
                const Icon = game.icon;
                return (
                  <motion.div
                    key={game.id}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: index * 0.1 }}
                  >
                    <Card className="p-4 sm:p-6 hover:shadow-xl transition-all cursor-pointer group"
                      onClick={() => startGame(game.id)}
                    >
                      <div className={`w-12 h-12 sm:w-16 sm:h-16 bg-gradient-to-br ${game.color} rounded-xl flex items-center justify-center mb-3 sm:mb-4 group-hover:scale-110 transition-transform`}>
                        <Icon className="w-6 h-6 sm:w-8 sm:h-8 text-white" />
                      </div>
                      <h3 className="text-lg sm:text-xl font-bold text-slate-900 mb-2">{game.name}</h3>
                      <p className="text-sm sm:text-base text-slate-600 mb-4">{game.description}</p>
                      <Button className="w-full min-h-[44px] sm:min-h-0 touch-target" size="sm">
                        {language === 'en' ? 'Play' : 'Jouer'}
                      </Button>
                    </Card>
                  </motion.div>
                );
              })}
            </div>
          ) : (
            /* Active Game */
            <div className="section-spacing">
              <div className="flex items-center justify-between">
                <Button variant="outline" onClick={() => setActiveGame(null)} className="min-h-[44px] sm:min-h-0 touch-target">
                  {language === 'en' ? '← Back' : '← Retour'}
                </Button>
                <Badge className="text-xs sm:text-sm">{games.find(g => g.id === activeGame)?.name}</Badge>
              </div>

              {loading ? (
                <Card className="p-8 sm:p-12 text-center">
                  <Loader2 className="w-10 h-10 sm:w-12 sm:h-12 animate-spin text-purple-600 mx-auto mb-4" />
                  <p className="text-sm sm:text-base text-slate-600">
                    {language === 'en' ? 'AI is thinking...' : 'L\'IA réfléchit...'}
                  </p>
                </Card>
              ) : (
                <>
                  {/* Riddle Game */}
                  {activeGame === "riddle" && gameState.riddle && (
                    <Card className="p-4 sm:p-6">
                      <div className="mb-4 sm:mb-6">
                        <h3 className="text-lg sm:text-xl font-bold text-slate-900 mb-3 sm:mb-4">
                          {language === 'en' ? 'Riddle:' : 'Énigme:'}
                        </h3>
                        <p className="text-base sm:text-lg text-slate-700 italic">"{gameState.riddle}"</p>
                      </div>

                      {!gameState.solved ? (
                        <div className="space-y-3 sm:space-y-4">
                          <div>
                            <Input
                              value={gameState.userAnswer || ""}
                              onChange={(e) => setGameState({ ...gameState, userAnswer: e.target.value })}
                              placeholder={language === 'en' ? "Your answer..." : "Votre réponse..."}
                              className="w-full text-base"
                              onKeyPress={(e) => e.key === 'Enter' && checkRiddleAnswer()}
                            />
                          </div>
                          
                          <div className="flex flex-col sm:flex-row gap-2 sm:gap-3">
                            <Button onClick={checkRiddleAnswer} className="flex-1 min-h-[44px] sm:min-h-0 touch-target">
                              <Check className="w-4 h-4 mr-2" />
                              {language === 'en' ? 'Check Answer' : 'Vérifier'}
                            </Button>
                            {gameState.hintsUsed < gameState.hints.length && (
                              <Button 
                                variant="outline" 
                                onClick={() => setGameState({ ...gameState, hintsUsed: gameState.hintsUsed + 1 })}
                                className="flex-1 min-h-[44px] sm:min-h-0 touch-target"
                              >
                                <Lightbulb className="w-4 h-4 mr-2" />
                                {language === 'en' ? 'Hint' : 'Indice'} ({gameState.hintsUsed + 1}/3)
                              </Button>
                            )}
                          </div>

                          {gameState.hintsUsed > 0 && (
                            <div className="bg-amber-50 p-3 sm:p-4 rounded-lg">
                              <p className="text-xs sm:text-sm font-semibold text-amber-900 mb-2">
                                {language === 'en' ? 'Hints:' : 'Indices:'}
                              </p>
                              {gameState.hints.slice(0, gameState.hintsUsed).map((hint, idx) => (
                                <p key={idx} className="text-xs sm:text-sm text-amber-800 mb-1">• {hint}</p>
                              ))}
                            </div>
                          )}

                          {gameState.attempts > 0 && (
                            <p className="text-xs sm:text-sm text-red-600">
                              {language === 'en' ? `Wrong answer. Attempts: ${gameState.attempts}` : `Mauvaise réponse. Tentatives: ${gameState.attempts}`}
                            </p>
                          )}
                        </div>
                      ) : (
                        <div className="bg-green-50 p-4 sm:p-6 rounded-lg text-center">
                          <Check className="w-10 h-10 sm:w-12 sm:h-12 text-green-600 mx-auto mb-3" />
                          <p className="text-lg sm:text-xl font-bold text-green-900 mb-2">
                            {language === 'en' ? 'Correct!' : 'Correct!'}
                          </p>
                          <p className="text-sm sm:text-base text-green-700">
                            {language === 'en' ? `Answer: ${gameState.answer}` : `Réponse: ${gameState.answer}`}
                          </p>
                          <Button onClick={generateRiddle} className="mt-4 min-h-[44px] sm:min-h-0 touch-target">
                            {language === 'en' ? 'Next Riddle' : 'Énigme Suivante'}
                          </Button>
                        </div>
                      )}
                    </Card>
                  )}

                  {/* Story Game */}
                  {activeGame === "story" && gameState.story && (
                    <Card className="p-4 sm:p-6">
                      <div className="mb-4 sm:mb-6">
                        <h3 className="text-lg sm:text-xl font-bold text-slate-900 mb-3 sm:mb-4">
                          {language === 'en' ? 'Your Story:' : 'Votre Histoire:'}
                        </h3>
                        <div className="space-y-3 sm:space-y-4 text-sm sm:text-base text-slate-700">
                          {gameState.chapters?.map((chapter, idx) => (
                            <p key={idx} className="leading-relaxed">{chapter}</p>
                          ))}
                        </div>
                      </div>

                      {!gameState.ended && gameState.choices?.length > 0 && (
                        <div className="space-y-2 sm:space-y-3">
                          <p className="font-semibold text-sm sm:text-base text-slate-900 mb-2 sm:mb-3">
                            {language === 'en' ? 'What do you do?' : 'Que faites-vous?'}
                          </p>
                          {gameState.choices.map((choice, idx) => (
                            <Button
                              key={idx}
                              variant="outline"
                              onClick={() => continueStory(choice)}
                              className="w-full text-left justify-start min-h-[56px] sm:min-h-0 touch-target text-sm sm:text-base"
                            >
                              {idx + 1}. {choice}
                            </Button>
                          ))}
                        </div>
                      )}

                      {gameState.ended && (
                        <div className="bg-purple-50 p-4 sm:p-6 rounded-lg text-center">
                          <BookOpen className="w-10 h-10 sm:w-12 sm:h-12 text-purple-600 mx-auto mb-3" />
                          <p className="text-lg sm:text-xl font-bold text-purple-900 mb-2">
                            {language === 'en' ? 'Story Complete!' : 'Histoire Terminée!'}
                          </p>
                          <Button onClick={startStory} className="mt-4 min-h-[44px] sm:min-h-0 touch-target">
                            {language === 'en' ? 'New Story' : 'Nouvelle Histoire'}
                          </Button>
                        </div>
                      )}
                    </Card>
                  )}

                  {/* Philosophy Game */}
                  {activeGame === "philosophy" && gameState.question && (
                    <Card className="p-4 sm:p-6">
                      <div className="mb-4 sm:mb-6">
                        <h3 className="text-lg sm:text-xl font-bold text-slate-900 mb-3 sm:mb-4">
                          {gameState.question}
                        </h3>
                      </div>

                      {!gameState.answered ? (
                        <div className="space-y-2 sm:space-y-3">
                          {gameState.options?.map((option, idx) => (
                            <Button
                              key={idx}
                              variant="outline"
                              onClick={() => answerPhilosophy(idx)}
                              className="w-full text-left justify-start min-h-[56px] sm:min-h-0 touch-target text-sm sm:text-base"
                            >
                              {String.fromCharCode(65 + idx)}. {option}
                            </Button>
                          ))}
                        </div>
                      ) : (
                        <div className={`p-4 sm:p-6 rounded-lg ${gameState.userChoice === gameState.bestAnswer ? 'bg-green-50' : 'bg-blue-50'}`}>
                          <p className="text-base sm:text-lg font-bold mb-3 sm:mb-4" style={{ color: gameState.userChoice === gameState.bestAnswer ? '#166534' : '#1e40af' }}>
                            {gameState.userChoice === gameState.bestAnswer 
                              ? (language === 'en' ? 'Excellent reasoning!' : 'Excellent raisonnement!') 
                              : (language === 'en' ? 'Interesting perspective!' : 'Perspective intéressante!')}
                          </p>
                          <p className="text-sm sm:text-base text-slate-700 mb-4">{gameState.explanation}</p>
                          <Button onClick={generatePhilosophyQuestion} className="min-h-[44px] sm:min-h-0 touch-target">
                            {language === 'en' ? 'Next Question' : 'Question Suivante'}
                          </Button>
                        </div>
                      )}
                    </Card>
                  )}

                  {/* Word Chain Game */}
                  {activeGame === "wordchain" && gameState.words && (
                    <Card className="p-4 sm:p-6">
                      <div className="mb-4 sm:mb-6">
                        <div className="flex items-center justify-between mb-4">
                          <Badge className="bg-blue-500 text-white">
                            {language === 'en' ? 'Round' : 'Manche'}: {gameState.round}
                          </Badge>
                          <div className="flex gap-2">
                            <Badge variant="outline">
                              {language === 'en' ? 'You' : 'Vous'}: {gameState.userScore}
                            </Badge>
                            <Badge variant="outline">
                              IA: {gameState.aiScore}
                            </Badge>
                          </div>
                        </div>
                        <p className="text-sm sm:text-base text-slate-600 mb-3">
                          <strong>{language === 'en' ? 'Rule:' : 'Règle:'}</strong> {gameState.rule}
                        </p>
                        <div className="bg-slate-50 p-3 sm:p-4 rounded-lg">
                          <p className="text-xs sm:text-sm font-semibold text-slate-900 mb-2">
                            {language === 'en' ? 'Word Chain:' : 'Chaîne de Mots:'}
                          </p>
                          <p className="text-sm sm:text-base text-slate-700">
                            {gameState.words.join(" → ")}
                          </p>
                        </div>
                      </div>

                      <div className="space-y-3">
                        <Input
                          placeholder={language === 'en' ? "Your word..." : "Votre mot..."}
                          onKeyPress={(e) => {
                            if (e.key === 'Enter' && e.target.value.trim()) {
                              submitWord(e.target.value.trim());
                              e.target.value = "";
                            }
                          }}
                          className="w-full text-base"
                        />
                        {gameState.error && (
                          <p className="text-xs sm:text-sm text-red-600">{gameState.error}</p>
                        )}
                      </div>
                    </Card>
                  )}

                  {/* Pattern Game */}
                  {activeGame === "pattern" && gameState.sequence && (
                    <Card className="p-4 sm:p-6">
                      <div className="mb-4 sm:mb-6">
                        <h3 className="text-lg sm:text-xl font-bold text-slate-900 mb-4">
                          {language === 'en' ? 'What comes next?' : 'Quel est le suivant?'}
                        </h3>
                        <div className="bg-gradient-to-r from-teal-50 to-green-50 p-4 sm:p-6 rounded-lg text-center">
                          <p className="text-xl sm:text-2xl font-mono font-bold text-slate-900">
                            {gameState.sequence.join(" , ")} , ?
                          </p>
                        </div>
                      </div>

                      {!gameState.answered ? (
                        <div className="space-y-3">
                          <Input
                            value={gameState.userAnswer}
                            onChange={(e) => setGameState({ ...gameState, userAnswer: e.target.value })}
                            placeholder={language === 'en' ? "Your answer..." : "Votre réponse..."}
                            onKeyPress={(e) => e.key === 'Enter' && checkPattern()}
                            className="w-full text-base"
                          />
                          <Button onClick={checkPattern} className="w-full min-h-[44px] touch-target">
                            {language === 'en' ? 'Submit & Compare' : 'Soumettre & Comparer'}
                          </Button>
                        </div>
                      ) : (
                        <div className="space-y-4">
                          <div className={`p-4 rounded-lg ${gameState.userCorrect ? 'bg-green-50' : 'bg-red-50'}`}>
                            <p className="font-semibold mb-2">
                              {language === 'en' ? 'Your answer:' : 'Votre réponse:'} {gameState.userAnswer}
                            </p>
                            <p className="text-sm">{gameState.userCorrect ? '✓ Correct!' : '✗ Incorrect'}</p>
                          </div>
                          <div className={`p-4 rounded-lg ${gameState.aiCorrect ? 'bg-green-50' : 'bg-red-50'}`}>
                            <p className="font-semibold mb-2">
                              {language === 'en' ? 'AI answer:' : 'Réponse IA:'} {gameState.aiAnswer}
                            </p>
                            <p className="text-sm">{gameState.aiCorrect ? '✓ Correct!' : '✗ Incorrect'}</p>
                          </div>
                          <div className="bg-blue-50 p-4 rounded-lg">
                            <p className="font-semibold mb-2">{language === 'en' ? 'Correct answer:' : 'Bonne réponse:'} {gameState.answer}</p>
                            <p className="text-sm text-slate-700">{gameState.explanation}</p>
                          </div>
                          <Badge className="text-lg">+{gameState.points} points</Badge>
                          <Button onClick={startPattern} className="w-full min-h-[44px] touch-target">
                            {language === 'en' ? 'Next Pattern' : 'Motif Suivant'}
                          </Button>
                        </div>
                      )}
                    </Card>
                  )}

                  {/* Creativity Game */}
                  {activeGame === "creativity" && gameState.challenge && (
                    <Card className="p-4 sm:p-6">
                      <div className="mb-4 sm:mb-6">
                        <h3 className="text-lg sm:text-xl font-bold text-slate-900 mb-4">
                          {language === 'en' ? 'Creative Challenge:' : 'Défi Créatif:'}
                        </h3>
                        <p className="text-base sm:text-lg text-slate-700 italic mb-4">"{gameState.challenge}"</p>
                        <div className="bg-pink-50 p-3 rounded-lg">
                          <p className="text-xs sm:text-sm font-semibold text-pink-900 mb-2">
                            {language === 'en' ? 'Criteria:' : 'Critères:'}
                          </p>
                          <ul className="text-xs sm:text-sm text-pink-800 list-disc list-inside">
                            {gameState.criteria.map((c, i) => <li key={i}>{c}</li>)}
                          </ul>
                        </div>
                      </div>

                      {!gameState.submitted ? (
                        <div className="space-y-3">
                          <Textarea
                            value={gameState.userResponse}
                            onChange={(e) => setGameState({ ...gameState, userResponse: e.target.value })}
                            placeholder={language === 'en' ? "Your creative response..." : "Votre réponse créative..."}
                            rows={5}
                            className="w-full"
                          />
                          <Button 
                            onClick={submitCreativity} 
                            disabled={!gameState.userResponse.trim()}
                            className="w-full min-h-[44px] touch-target"
                          >
                            {language === 'en' ? 'Submit & Compare' : 'Soumettre & Comparer'}
                          </Button>
                        </div>
                      ) : (
                        <div className="space-y-4">
                          <div className="bg-purple-50 p-4 rounded-lg">
                            <p className="font-semibold mb-2">{language === 'en' ? 'Your Response:' : 'Votre Réponse:'}</p>
                            <p className="text-sm mb-3">{gameState.userResponse}</p>
                            <div className="flex gap-2">
                              {gameState.evaluation.user_scores.map((s, i) => (
                                <Badge key={i}>{gameState.criteria[i]}: {s}/10</Badge>
                              ))}
                            </div>
                            <p className="text-lg font-bold mt-2">Total: {gameState.userTotal}/30</p>
                          </div>
                          
                          <div className="bg-indigo-50 p-4 rounded-lg">
                            <p className="font-semibold mb-2">{language === 'en' ? 'AI Response:' : 'Réponse IA:'}</p>
                            <p className="text-sm mb-3">{gameState.aiResponse}</p>
                            <div className="flex gap-2">
                              {gameState.evaluation.ai_scores.map((s, i) => (
                                <Badge key={i}>{gameState.criteria[i]}: {s}/10</Badge>
                              ))}
                            </div>
                            <p className="text-lg font-bold mt-2">Total: {gameState.aiTotal}/30</p>
                          </div>

                          <div className={`p-4 rounded-lg text-center ${
                            gameState.evaluation.winner === 'user' ? 'bg-green-50' :
                            gameState.evaluation.winner === 'tie' ? 'bg-yellow-50' : 'bg-red-50'
                          }`}>
                            <Trophy className="w-12 h-12 mx-auto mb-2" />
                            <p className="text-xl font-bold">
                              {gameState.evaluation.winner === 'user' ? (language === 'en' ? 'You Win!' : 'Vous Gagnez!') :
                               gameState.evaluation.winner === 'tie' ? (language === 'en' ? 'Tie!' : 'Égalité!') :
                               (language === 'en' ? 'AI Wins!' : 'IA Gagne!')}
                            </p>
                            <p className="text-sm mt-2">{gameState.evaluation.feedback}</p>
                          </div>

                          <Button onClick={startCreativity} className="w-full min-h-[44px] touch-target">
                            {language === 'en' ? 'New Challenge' : 'Nouveau Défi'}
                          </Button>
                        </div>
                      )}
                    </Card>
                  )}

                  {/* Quick Quiz Game */}
                  {activeGame === "quickquiz" && gameState.questions && (
                    <Card className="p-4 sm:p-6">
                      {!gameState.finished ? (
                        <>
                          <div className="mb-4 sm:mb-6">
                            <div className="flex items-center justify-between mb-4">
                              <Badge>
                                {language === 'en' ? 'Question' : 'Question'} {gameState.currentQuestion + 1}/{gameState.questions.length}
                              </Badge>
                              <div className="flex gap-2">
                                <Badge variant="outline">Vous: {gameState.userScore}</Badge>
                                <Badge variant="outline">IA: {gameState.aiScore}</Badge>
                              </div>
                            </div>
                            <Progress value={(gameState.currentQuestion / gameState.questions.length) * 100} className="mb-4" />
                            <h3 className="text-lg sm:text-xl font-bold text-slate-900">
                              {gameState.questions[gameState.currentQuestion].question}
                            </h3>
                          </div>

                          <div className="space-y-2">
                            {gameState.questions[gameState.currentQuestion].options.map((opt, idx) => (
                              <Button
                                key={idx}
                                variant="outline"
                                onClick={() => answerQuickQuiz(idx)}
                                className="w-full text-left justify-start min-h-[56px] touch-target text-sm sm:text-base"
                              >
                                {String.fromCharCode(65 + idx)}. {opt}
                              </Button>
                            ))}
                          </div>
                        </>
                      ) : (
                        <div className="text-center space-y-4">
                          <Trophy className="w-16 h-16 mx-auto text-amber-500" />
                          <h3 className="text-2xl font-bold">
                            {gameState.userScore > gameState.aiScore ? 
                              (language === 'en' ? 'You Win!' : 'Vous Gagnez!') :
                              gameState.userScore === gameState.aiScore ?
                              (language === 'en' ? 'Tie!' : 'Égalité!') :
                              (language === 'en' ? 'AI Wins!' : 'IA Gagne!')}
                          </h3>
                          <div className="flex justify-center gap-4">
                            <div className="bg-blue-50 p-4 rounded-lg">
                              <p className="font-semibold">{language === 'en' ? 'Your Score' : 'Votre Score'}</p>
                              <p className="text-3xl font-bold">{gameState.userScore}</p>
                            </div>
                            <div className="bg-purple-50 p-4 rounded-lg">
                              <p className="font-semibold">{language === 'en' ? 'AI Score' : 'Score IA'}</p>
                              <p className="text-3xl font-bold">{gameState.aiScore}</p>
                            </div>
                          </div>
                          <Button onClick={startQuickQuiz} className="min-h-[44px] touch-target">
                            {language === 'en' ? 'Play Again' : 'Rejouer'}
                          </Button>
                        </div>
                      )}
                    </Card>
                  )}

                  {/* Guess Game */}
                  {activeGame === "guess" && gameState.thought && (
                    <Card className="p-4 sm:p-6">
                      <div className="mb-4 sm:mb-6">
                        <h3 className="text-lg sm:text-xl font-bold text-slate-900 mb-3 sm:mb-4">
                          {language === 'en' ? 'I\'m thinking of something...' : 'Je pense à quelque chose...'}
                        </h3>
                      </div>

                      {!gameState.solved ? (
                        <div className="space-y-3 sm:space-y-4">
                          <div className="bg-indigo-50 p-3 sm:p-4 rounded-lg">
                            <p className="text-xs sm:text-sm font-semibold text-indigo-900 mb-2">
                              {language === 'en' ? `Clue ${gameState.currentClue + 1}:` : `Indice ${gameState.currentClue + 1}:`}
                            </p>
                            <p className="text-sm sm:text-base text-indigo-800">{gameState.clues[gameState.currentClue]}</p>
                          </div>

                          <Input
                            value={gameState.userGuess || ""}
                            onChange={(e) => setGameState({ ...gameState, userGuess: e.target.value })}
                            placeholder={language === 'en' ? "Your guess..." : "Votre supposition..."}
                            className="w-full text-base"
                            onKeyPress={(e) => e.key === 'Enter' && checkGuess()}
                          />

                          <div className="flex flex-col sm:flex-row gap-2 sm:gap-3">
                            <Button onClick={checkGuess} className="flex-1 min-h-[44px] sm:min-h-0 touch-target">
                              <Target className="w-4 h-4 mr-2" />
                              {language === 'en' ? 'Guess' : 'Deviner'}
                            </Button>
                            {gameState.currentClue < gameState.clues.length - 1 && (
                              <Button variant="outline" onClick={showNextClue} className="flex-1 min-h-[44px] sm:min-h-0 touch-target">
                                <Lightbulb className="w-4 h-4 mr-2" />
                                {language === 'en' ? 'Next Clue' : 'Indice Suivant'}
                              </Button>
                            )}
                          </div>

                          {gameState.attempts > 0 && (
                            <p className="text-xs sm:text-sm text-red-600">
                              {language === 'en' ? `Wrong! Attempts: ${gameState.attempts}` : `Raté! Tentatives: ${gameState.attempts}`}
                            </p>
                          )}
                        </div>
                      ) : (
                        <div className="bg-green-50 p-4 sm:p-6 rounded-lg text-center">
                          <Check className="w-10 h-10 sm:w-12 sm:h-12 text-green-600 mx-auto mb-3" />
                          <p className="text-lg sm:text-xl font-bold text-green-900 mb-2">
                            {language === 'en' ? 'You guessed it!' : 'Vous avez trouvé!'}
                          </p>
                          <p className="text-sm sm:text-base text-green-700">
                            {language === 'en' ? `I was thinking of: ${gameState.thought}` : `Je pensais à: ${gameState.thought}`}
                          </p>
                          <Button onClick={generateThought} className="mt-4 min-h-[44px] sm:min-h-0 touch-target">
                            {language === 'en' ? 'Play Again' : 'Rejouer'}
                          </Button>
                        </div>
                      )}
                    </Card>
                  )}
                </>
              )}
            </div>
          )}
        </div>
      </div>
    </PageTransition>
  );
}