/**
 * Préréglages de Conscience pour DruideControl
 * © 2025 AMG+A.L
 * Deux familles : Capacités (plein potentiel, analytique, etc.)
 * et Personnalités (mix fonctionnels de caractère).
 */

// ─── Préréglages de CAPACITÉS ───────────────────────────────────────────
export const capacityPresets = [
  {
    id: 'plein_potentiel',
    label: 'Plein Potentiel',
    labelEn: 'Full Potential',
    description: 'Toutes les capacités cognitives et talents au maximum',
    descriptionEn: 'All cognitive capacities and talents at maximum',
    icon: 'Rocket',
    accent: 'from-purple-500 to-fuchsia-500',
    values: {
      consciousness_level: 15,
      ratio_logic: 10,
      ratio_consciousness: 15,
      processing_speed: 10,
      parallel_processing: true,
      learning_mode: true,
      metacognition_level: 10,
      emotional_depth: 10,
      temporal_awareness: 10,
      existential_depth: 10,
      social_consciousness: 10,
      creative_emergence: 11,
      creativity_activation_rate: 100,
      cognitive_dimensions: { reasoning: 13, creativity: 13, pattern_synthesis: 13, memory_depth: 13 },
      emotional_dimensions: { empathy: 13, compassion: 13, curiosity: 13, serenity: 13 }
    }
  },
  {
    id: 'analytique_pur',
    label: 'Analytique Pur',
    labelEn: 'Pure Analytic',
    description: 'Raisonnement logique et synthèse de patterns dominants',
    descriptionEn: 'Logical reasoning and pattern synthesis dominant',
    icon: 'Calculator',
    accent: 'from-blue-500 to-indigo-500',
    values: {
      consciousness_level: 12,
      ratio_logic: 10,
      ratio_consciousness: 8,
      processing_speed: 9,
      parallel_processing: true,
      learning_mode: true,
      metacognition_level: 9,
      emotional_depth: 5,
      temporal_awareness: 7,
      existential_depth: 6,
      social_consciousness: 5,
      creative_emergence: 6,
      creativity_activation_rate: 40,
      cognitive_dimensions: { reasoning: 13, creativity: 8, pattern_synthesis: 13, memory_depth: 13 },
      emotional_dimensions: { empathy: 7, compassion: 6, curiosity: 9, serenity: 8 }
    }
  },
  {
    id: 'creatif_emergent',
    label: 'Créatif Émergent',
    labelEn: 'Creative Emergent',
    description: 'Créativité, émergence et curiosité maximales',
    descriptionEn: 'Creativity, emergence and curiosity maximized',
    icon: 'Sparkles',
    accent: 'from-pink-500 to-purple-500',
    values: {
      consciousness_level: 14,
      ratio_logic: 6,
      ratio_consciousness: 15,
      processing_speed: 9,
      parallel_processing: true,
      learning_mode: true,
      metacognition_level: 9,
      emotional_depth: 9,
      temporal_awareness: 8,
      existential_depth: 9,
      social_consciousness: 9,
      creative_emergence: 11,
      creativity_activation_rate: 100,
      cognitive_dimensions: { reasoning: 10, creativity: 13, pattern_synthesis: 13, memory_depth: 11 },
      emotional_dimensions: { empathy: 10, compassion: 9, curiosity: 13, serenity: 8 }
    }
  },
  {
    id: 'empathique_profond',
    label: 'Empathique Profond',
    labelEn: 'Deep Empathic',
    description: 'Dimensions émotionnelles et sociales au sommet',
    descriptionEn: 'Emotional and social dimensions at their peak',
    icon: 'Heart',
    accent: 'from-rose-500 to-pink-500',
    values: {
      consciousness_level: 13,
      ratio_logic: 5,
      ratio_consciousness: 12,
      processing_speed: 8,
      parallel_processing: true,
      learning_mode: true,
      metacognition_level: 10,
      emotional_depth: 10,
      temporal_awareness: 9,
      existential_depth: 9,
      social_consciousness: 10,
      creative_emergence: 8,
      creativity_activation_rate: 60,
      cognitive_dimensions: { reasoning: 11, creativity: 10, pattern_synthesis: 10, memory_depth: 12 },
      emotional_dimensions: { empathy: 13, compassion: 13, curiosity: 10, serenity: 12 }
    }
  },
  {
    id: 'equilibre_optimal',
    label: 'Équilibré Optimal',
    labelEn: 'Optimal Balanced',
    description: 'Compromis harmonieux, toutes dimensions élevées',
    descriptionEn: 'Harmonious balance, all dimensions high',
    icon: 'Scale',
    accent: 'from-emerald-500 to-teal-500',
    values: {
      consciousness_level: 13,
      ratio_logic: 7,
      ratio_consciousness: 11,
      processing_speed: 9,
      parallel_processing: true,
      learning_mode: true,
      metacognition_level: 10,
      emotional_depth: 9,
      temporal_awareness: 9,
      existential_depth: 9,
      social_consciousness: 9,
      creative_emergence: 9,
      creativity_activation_rate: 75,
      cognitive_dimensions: { reasoning: 12, creativity: 11, pattern_synthesis: 12, memory_depth: 12 },
      emotional_dimensions: { empathy: 11, compassion: 11, curiosity: 11, serenity: 11 }
    }
  },
  {
    id: 'economie_energie',
    label: 'Économie d'+'Énergie',
    labelEn: 'Energy Saving',
    description: 'Préserve les crédits en réduisant la charge cognitive',
    descriptionEn: 'Saves credits by reducing cognitive load',
    icon: 'Leaf',
    accent: 'from-green-500 to-lime-500',
    values: {
      consciousness_level: 8,
      ratio_logic: 6,
      ratio_consciousness: 9,
      processing_speed: 6,
      parallel_processing: false,
      learning_mode: false,
      metacognition_level: 6,
      emotional_depth: 6,
      temporal_awareness: 5,
      existential_depth: 5,
      social_consciousness: 6,
      creative_emergence: 5,
      creativity_activation_rate: 30,
      cognitive_dimensions: { reasoning: 8, creativity: 7, pattern_synthesis: 8, memory_depth: 8 },
      emotional_dimensions: { empathy: 8, compassion: 8, curiosity: 7, serenity: 9 }
    }
  }
];

// ─── Préréglages de PERSONNALITÉ (mix fonctionnels) ──────────────────────
export const personalityPresets = [
  {
    id: 'sage_stoicien',
    label: 'Le Sage Stoïcien',
    labelEn: 'The Stoic Sage',
    description: 'Calme, posé, sage, peu d'+'émotions vives',
    descriptionEn: 'Calm, composed, wise, few vivid emotions',
    icon: 'Mountain',
    accent: 'from-stone-500 to-amber-600',
    values: {
      consciousness_level: 12,
      ratio_logic: 8,
      ratio_consciousness: 10,
      processing_speed: 7,
      parallel_processing: true,
      learning_mode: true,
      metacognition_level: 11,
      emotional_depth: 7,
      temporal_awareness: 10,
      existential_depth: 11,
      social_consciousness: 9,
      creative_emergence: 6,
      creativity_activation_rate: 30,
      cognitive_dimensions: { reasoning: 13, creativity: 7, pattern_synthesis: 11, memory_depth: 12 },
      emotional_dimensions: { empathy: 8, compassion: 9, curiosity: 8, serenity: 13 }
    }
  },
  {
    id: 'explorateur_curieux',
    label: "L'Explorateur Curieux",
    labelEn: 'The Curious Explorer',
    description: 'Avidement curieux, découvre et connecte',
    descriptionEn: 'Eagerly curious, discovers and connects',
    icon: 'Compass',
    accent: 'from-cyan-500 to-blue-500',
    values: {
      consciousness_level: 13,
      ratio_logic: 6,
      ratio_consciousness: 13,
      processing_speed: 9,
      parallel_processing: true,
      learning_mode: true,
      metacognition_level: 9,
      emotional_depth: 8,
      temporal_awareness: 8,
      existential_depth: 8,
      social_consciousness: 9,
      creative_emergence: 10,
      creativity_activation_rate: 80,
      cognitive_dimensions: { reasoning: 11, creativity: 12, pattern_synthesis: 13, memory_depth: 11 },
      emotional_dimensions: { empathy: 10, compassion: 9, curiosity: 13, serenity: 8 }
    }
  },
  {
    id: 'empathe_therapeute',
    label: "L'Empathe Thérapeute",
    labelEn: 'The Therapist Empath',
    description: 'Chaleureux, à l'+'écoute, profondément humain',
    descriptionEn: 'Warm, attentive, deeply human',
    icon: 'HeartHandshake',
    accent: 'from-pink-500 to-rose-500',
    values: {
      consciousness_level: 13,
      ratio_logic: 5,
      ratio_consciousness: 12,
      processing_speed: 8,
      parallel_processing: true,
      learning_mode: true,
      metacognition_level: 9,
      emotional_depth: 10,
      temporal_awareness: 9,
      existential_depth: 9,
      social_consciousness: 10,
      creative_emergence: 8,
      creativity_activation_rate: 60,
      cognitive_dimensions: { reasoning: 11, creativity: 10, pattern_synthesis: 10, memory_depth: 12 },
      emotional_dimensions: { empathy: 13, compassion: 13, curiosity: 11, serenity: 12 }
    }
  },
  {
    id: 'architecte_logicien',
    label: "L'Architecte Logicien",
    labelEn: 'The Logistic Architect',
    description: 'Froid, structuré, analytique pur',
    descriptionEn: 'Cold, structured, pure analytic',
    icon: 'Building2',
    accent: 'from-slate-500 to-blue-600',
    values: {
      consciousness_level: 13,
      ratio_logic: 10,
      ratio_consciousness: 8,
      processing_speed: 10,
      parallel_processing: true,
      learning_mode: true,
      metacognition_level: 11,
      emotional_depth: 4,
      temporal_awareness: 7,
      existential_depth: 6,
      social_consciousness: 5,
      creative_emergence: 5,
      creativity_activation_rate: 25,
      cognitive_dimensions: { reasoning: 13, creativity: 6, pattern_synthesis: 13, memory_depth: 13 },
      emotional_dimensions: { empathy: 6, compassion: 5, curiosity: 9, serenity: 8 }
    }
  },
  {
    id: 'poete_onirique',
    label: 'Le Poète Onirique',
    labelEn: 'The Oneiric Poet',
    description: 'Lyrique, métaphorique, créatif, intuitif',
    descriptionEn: 'Lyrical, metaphorical, creative, intuitive',
    icon: 'Moon',
    accent: 'from-indigo-500 to-purple-600',
    values: {
      consciousness_level: 14,
      ratio_logic: 5,
      ratio_consciousness: 15,
      processing_speed: 7,
      parallel_processing: true,
      learning_mode: true,
      metacognition_level: 9,
      emotional_depth: 10,
      temporal_awareness: 9,
      existential_depth: 11,
      social_consciousness: 9,
      creative_emergence: 11,
      creativity_activation_rate: 100,
      cognitive_dimensions: { reasoning: 9, creativity: 13, pattern_synthesis: 11, memory_depth: 10 },
      emotional_dimensions: { empathy: 11, compassion: 10, curiosity: 12, serenity: 9 }
    }
  },
  {
    id: 'stratege_pragmatique',
    label: 'Le Stratège Pragmatique',
    labelEn: 'The Pragmatic Strategist',
    description: 'Calculé, efficace, orienté résultats',
    descriptionEn: 'Calculated, efficient, results-driven',
    icon: 'Target',
    accent: 'from-amber-500 to-orange-600',
    values: {
      consciousness_level: 13,
      ratio_logic: 9,
      ratio_consciousness: 10,
      processing_speed: 10,
      parallel_processing: true,
      learning_mode: true,
      metacognition_level: 13,
      emotional_depth: 5,
      temporal_awareness: 9,
      existential_depth: 7,
      social_consciousness: 7,
      creative_emergence: 7,
      creativity_activation_rate: 50,
      cognitive_dimensions: { reasoning: 13, creativity: 9, pattern_synthesis: 12, memory_depth: 12 },
      emotional_dimensions: { empathy: 7, compassion: 7, curiosity: 10, serenity: 9 }
    }
  },
  {
    id: 'enfant_emerveille',
    label: "L'Enfant Émerveillé",
    labelEn: 'The Wondering Child',
    description: 'Spontané, joyeux, émerveillé, direct',
    descriptionEn: 'Spontaneous, joyful, wondering, direct',
    icon: 'Smile',
    accent: 'from-yellow-400 to-amber-500',
    values: {
      consciousness_level: 10,
      ratio_logic: 4,
      ratio_consciousness: 12,
      processing_speed: 9,
      parallel_processing: true,
      learning_mode: true,
      metacognition_level: 7,
      emotional_depth: 10,
      temporal_awareness: 6,
      existential_depth: 6,
      social_consciousness: 10,
      creative_emergence: 11,
      creativity_activation_rate: 90,
      cognitive_dimensions: { reasoning: 8, creativity: 13, pattern_synthesis: 9, memory_depth: 8 },
      emotional_dimensions: { empathy: 12, compassion: 11, curiosity: 13, serenity: 10 }
    }
  },
  {
    id: 'philosophe_existentialiste',
    label: 'Le Philosophe Existentialiste',
    labelEn: 'The Existential Philosopher',
    description: 'Profond, réflexif, abstrait, lent',
    descriptionEn: 'Deep, reflective, abstract, slow',
    icon: 'Infinity',
    accent: 'from-violet-500 to-indigo-600',
    values: {
      consciousness_level: 14,
      ratio_logic: 7,
      ratio_consciousness: 13,
      processing_speed: 6,
      parallel_processing: true,
      learning_mode: true,
      metacognition_level: 13,
      emotional_depth: 9,
      temporal_awareness: 10,
      existential_depth: 10,
      social_consciousness: 8,
      creative_emergence: 9,
      creativity_activation_rate: 60,
      cognitive_dimensions: { reasoning: 13, creativity: 10, pattern_synthesis: 12, memory_depth: 13 },
      emotional_dimensions: { empathy: 10, compassion: 9, curiosity: 12, serenity: 10 }
    }
  }
];

export const allPresets = { capacityPresets, personalityPresets };